import React from "react";
import Link from "next/link";
import Image from "next/image";
import { routes } from "@/routes";
import RegisterForm from "./components/RegisterForm";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Register | Giugno Distribuciones",
    description: "Generated by create next app",
};

const page = () => {
    return(
        <>
        <Link href={routes.home} className="flex items-center space-x-3 rtl:space-x-reverse">
<Image
            src="/images/app-logo.png" 
            alt="Giugno-Distribuciones" 
            width={40} 
            height={40} 
            className="h-10" 
        />
</Link>
        <h1 className="text-xl font-bold mb-4">Registro de usuario</h1>
        <RegisterForm />
        </>
    )
}

export default page;