import React from "react";
import Image from "next/image";
import LoginFormUI from "./components/LoginFormUI";
import Link from "next/link";
import { routes } from "@/routes";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Login | Giugno Distribuciones",
    description: "Generated by create next app",
};

const LogingPage = () => {
    return (
        <>
        <Link href={routes.home} className="flex items-center space-x-3 rtl:space-x-reverse">
<Image
            src="/images/app-logo.png" 
            alt="Giugno-Distribuciones" 
            width={40} 
            height={40} 
            className="h-10" 
        />
</Link>
        <h1 className="text-xl font-bold mb-4">Inicio de sesión</h1>
        <LoginFormUI />
        </>
    );
};

export default LogingPage;